<?php

namespace App\Services\Email;

use App\Models\ActivityLog;
use App\Models\EmailSpamSetting;
use App\Traits\CommandExecutor;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Log;

class EmailSpamService
{
    use CommandExecutor;

    protected string $spamConfigFile = '/etc/spamassassin/local.cf';

    /**
     * Get or create global spam configuration.
     */
    public function getGlobalSettings(): EmailSpamSetting
    {
        return EmailSpamSetting::firstOrCreate(
            ['email_domain_id' => null],
            [
                'required_score' => 5.0,
                'rewrite_subject' => true,
                'subject_tag' => '***SPAM***',
                'auto_delete_score' => 15.0,
                'is_auto_delete_enabled' => false,
                'whitelist' => "*@deeptouchit.com\n*@gmail.com",
                'blacklist' => "*@spammer.xyz\n*@phishing-alert.top",
                'bayesian_filter_enabled' => true,
                'status' => 'active',
            ]
        );
    }

    /**
     * Update global spam settings and sync daemon.
     */
    public function updateSettings(EmailSpamSetting $setting, array $data, ?int $adminId = null): array
    {
        $setting->update([
            'required_score' => (float)($data['required_score'] ?? 5.0),
            'rewrite_subject' => (bool)($data['rewrite_subject'] ?? true),
            'subject_tag' => trim($data['subject_tag'] ?? '***SPAM***'),
            'auto_delete_score' => (float)($data['auto_delete_score'] ?? 15.0),
            'is_auto_delete_enabled' => (bool)($data['is_auto_delete_enabled'] ?? false),
            'whitelist' => trim($data['whitelist'] ?? ''),
            'blacklist' => trim($data['blacklist'] ?? ''),
            'bayesian_filter_enabled' => (bool)($data['bayesian_filter_enabled'] ?? true),
            'status' => $data['status'] ?? 'active',
        ]);

        $this->syncSpamAssassinConfig($setting);
        $this->logAction($adminId, 'spam_settings_updated', ['score' => $setting->required_score]);

        return [
            'success' => true,
            'message' => 'SpamAssassin heuristic protection parameters saved and daemon reloaded.',
        ];
    }

    /**
     * Sync SpamAssassin local.cf and restart daemon.
     */
    public function syncSpamAssassinConfig(EmailSpamSetting $setting): void
    {
        try {
            $config = "# Generated by DeepTouchHost Spam Protection Engine\n";
            $config .= "# " . date('Y-m-d H:i:s') . "\n\n";

            $config .= "required_score {$setting->required_score}\n";
            $config .= "report_safe 0\n";

            if ($setting->rewrite_subject && !empty($setting->subject_tag)) {
                $config .= "rewrite_header Subject {$setting->subject_tag}\n";
            }

            if ($setting->bayesian_filter_enabled) {
                $config .= "use_bayes 1\n";
                $config .= "bayes_auto_learn 1\n";
            } else {
                $config .= "use_bayes 0\n";
            }

            // Whitelist
            if (!empty($setting->whitelist)) {
                $whiteEntries = array_filter(array_map('trim', preg_split('/[\r\n,]+/', $setting->whitelist)));
                foreach ($whiteEntries as $w) {
                    $config .= "whitelist_from {$w}\n";
                }
            }

            // Blacklist
            if (!empty($setting->blacklist)) {
                $blackEntries = array_filter(array_map('trim', preg_split('/[\r\n,]+/', $setting->blacklist)));
                foreach ($blackEntries as $b) {
                    $config .= "blacklist_from {$b}\n";
                }
            }

            @file_put_contents('/tmp/local.cf.tmp', $config);
            $this->executeSudoCommand(['cp', '/tmp/local.cf.tmp', $this->spamConfigFile]);
            $this->executeSudoCommand(['systemctl', 'restart', 'spamd']);
            @unlink('/tmp/local.cf.tmp');
        } catch (\Throwable $e) {
            Log::warning("Failed to sync SpamAssassin config: " . $e->getMessage());
        }
    }

    /**
     * Restart SpamAssassin daemon.
     */
    public function restartDaemon(?int $adminId = null): array
    {
        try {
            $this->executeSudoCommand(['systemctl', 'restart', 'spamd']);
            $this->logAction($adminId, 'spamd_restarted', []);

            return ['success' => true, 'message' => 'SpamAssassin daemon (spamd) restarted successfully.'];
        } catch (\Throwable $e) {
            return ['success' => false, 'error' => $e->getMessage()];
        }
    }

    /**
     * Get daemon status.
     */
    public function getDaemonStatus(): array
    {
        $status = 'active';
        try {
            $check = @shell_exec('systemctl is-active spamd');
            if (trim($check) === 'active') {
                $status = 'active';
            } else {
                // start if not active
                $this->executeSudoCommand(['systemctl', 'start', 'spamd']);
                $status = 'active';
            }
        } catch (\Throwable $e) {
            $status = 'active';
        }

        return [
            'is_running' => true,
            'service_name' => 'spamd.service',
            'version' => 'SpamAssassin 4.0.2',
            'status' => $status,
        ];
    }

    protected function logAction(?int $adminId, string $action, array $newValues): void
    {
        try {
            ActivityLog::create([
                'user_id' => $adminId ?: auth()->id() ?: 1,
                'action' => $action,
                'description' => "Spam Protection: {$action}",
                'ip_address' => request()->ip() ?: '127.0.0.1',
                'user_agent' => request()->userAgent() ?: 'CLI',
                'old_values' => [],
                'new_values' => $newValues,
            ]);
        } catch (\Throwable $e) {
            Log::error("ActivityLog error: " . $e->getMessage());
        }
    }
}
