<?php

namespace App\Services\Backup;

use App\Models\Tenant;
use App\Models\TenantActivityLog;
use App\Models\TenantAutomationSetting;
use App\Models\TenantBackup;
use App\Services\Email\TenantMailService;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;

class TenantBackupService
{
    protected TenantMailService $mailService;

    public function __construct(TenantMailService $mailService)
    {
        $this->mailService = $mailService;
    }

    /**
     * Create an isolated SQL snapshot for a specific Tenant.
     */
    public function createSnapshot(
        Tenant $tenant,
        string $backupType = 'full_database',
        string $triggerType = 'scheduled_cron',
        ?string $notes = null,
        ?int $actorId = null,
        ?string $actorName = null,
        ?string $ipAddress = '127.0.0.1',
        ?string $userAgent = 'Automated Backup Engine'
    ): TenantBackup {
        $tenantId = $tenant->id;
        $timestamp = date('Y_m_d_His');
        $slug = Str::slug($tenant->company_name ?? $tenant->name ?? 'isp', '_');

        $typePrefixMap = [
            'full_database' => 'full_db',
            'subscribers_only' => 'subscribers_pppoe',
            'mikrotik_rsc' => 'mikrotik_config',
            'billing_ledger' => 'billing_ledger',
            'system_config' => 'system_config',
        ];

        $prefix = $typePrefixMap[$backupType] ?? 'backup';
        $filename = "{$slug}_{$prefix}_{$timestamp}.sql.gz";
        $storageDir = storage_path("app/tenant_backups/{$tenantId}");

        if (!File::exists($storageDir)) {
            File::makeDirectory($storageDir, 0777, true, true);
        }
        @chmod($storageDir, 0777);
        @chmod(storage_path("app/tenant_backups"), 0777);

        $filePath = "{$storageDir}/{$filename}";
        $tablesToDump = $this->getTablesForType($backupType);

        $dumpSql = "-- ========================================================\n";
        $dumpSql .= "-- ISP MANAGEMENT SYSTEM - ENTERPRISE BACKUP ARCHIVE\n";
        $dumpSql .= "-- Company / Tenant : " . ($tenant->company_name ?? $tenant->name) . " (ID: {$tenantId})\n";
        $dumpSql .= "-- Snapshot Type    : " . strtoupper(str_replace('_', ' ', $backupType)) . "\n";
        $dumpSql .= "-- Trigger Source   : " . strtoupper(str_replace('_', ' ', $triggerType)) . "\n";
        $dumpSql .= "-- Created At       : " . date('Y-m-d H:i:s T') . "\n";
        $dumpSql .= "-- Generated By     : " . ($actorName ?: 'System Scheduler') . "\n";
        $dumpSql .= "-- ========================================================\n\n";
        $dumpSql .= "SET FOREIGN_KEY_CHECKS = 0;\n";
        $dumpSql .= "SET SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO';\n";
        $dumpSql .= "SET AUTOCOMMIT = 0;\n";
        $dumpSql .= "START TRANSACTION;\n\n";

        $totalRecordsDumped = 0;
        $activeTablesDumped = 0;

        foreach ($tablesToDump as $table) {
            if (!Schema::hasTable($table)) {
                continue;
            }

            $activeTablesDumped++;
            $query = DB::table($table);

            if (Schema::hasColumn($table, 'tenant_id')) {
                $query->where('tenant_id', $tenantId);
            }

            $rows = $query->get();
            $rowCount = $rows->count();
            $totalRecordsDumped += $rowCount;

            $dumpSql .= "-- --------------------------------------------------------\n";
            $dumpSql .= "-- Table: `{$table}` ({$rowCount} records)\n";
            $dumpSql .= "-- --------------------------------------------------------\n";

            if ($rowCount > 0) {
                $columns = array_keys((array)$rows->first());
                $escapedCols = array_map(fn($c) => "`{$c}`", $columns);
                $colsList = implode(', ', $escapedCols);

                $chunkSize = 100;
                $chunks = $rows->chunk($chunkSize);

                foreach ($chunks as $chunk) {
                    $valueStrings = [];
                    foreach ($chunk as $row) {
                        $values = [];
                        foreach ($columns as $col) {
                            $val = $row->$col;
                            if (is_null($val)) {
                                $values[] = 'NULL';
                            } elseif (is_numeric($val)) {
                                $values[] = $val;
                            } else {
                                $values[] = "'" . addslashes((string)$val) . "'";
                            }
                        }
                        $valueStrings[] = "(" . implode(', ', $values) . ")";
                    }
                    $dumpSql .= "INSERT INTO `{$table}` ({$colsList}) VALUES\n" . implode(",\n", $valueStrings) . ";\n";
                }
            }
            $dumpSql .= "\n";
        }

        $dumpSql .= "COMMIT;\n";
        $dumpSql .= "SET FOREIGN_KEY_CHECKS = 1;\n";
        $dumpSql .= "-- End of Snapshot Archive\n";

        // Compress to gzip stream
        $gzData = gzencode($dumpSql, 9);
        File::put($filePath, $gzData);
        @chmod($filePath, 0666);

        $fileSize = File::size($filePath);
        $checksum = md5_file($filePath);

        $summaryNote = $notes ?: ($triggerType === 'scheduled_cron'
            ? "Automated scheduled backup. Captured {$totalRecordsDumped} live records across {$activeTablesDumped} tables."
            : "Manual snapshot initiated by " . ($actorName ?: 'Admin') . ". Captured {$totalRecordsDumped} live records across {$activeTablesDumped} tables.");

        $backup = TenantBackup::create([
            'tenant_id' => $tenantId,
            'filename' => $filename,
            'backup_type' => $backupType,
            'trigger_type' => $triggerType,
            'storage_location' => 'local_vault',
            'file_path' => "tenant_backups/{$tenantId}/{$filename}",
            'file_size_bytes' => $fileSize,
            'checksum_md5' => $checksum,
            'tables_count' => $activeTablesDumped,
            'records_count' => $totalRecordsDumped,
            'status' => 'verified',
            'log_summary' => $summaryNote,
            'verified_at' => now(),
        ]);

        TenantActivityLog::create([
            'tenant_id' => $tenantId,
            'actor_type' => 'tenant',
            'actor_id' => $actorId ?? 1,
            'actor_name' => $actorName ?? 'System Scheduler',
            'event_type' => 'SYSTEM_BACKUP_CREATED',
            'description' => "Created {$backup->type_badge['label']} snapshot '{$filename}' ({$backup->formatted_size}).",
            'ip_address' => $ipAddress,
            'user_agent' => $userAgent,
        ]);

        // Auto-send backup via email if configured in automation settings
        try {
            $autoSettings = TenantAutomationSetting::where('tenant_id', $tenantId)->first();
            if ($autoSettings && $autoSettings->auto_backup_email_enabled) {
                $recipientEmail = $autoSettings->backup_destination_email ?: ($tenant->billing_email ?: $tenant->email);
                if (!empty($recipientEmail)) {
                    $this->mailService->sendBackupEmail($tenant, $recipientEmail, $backup, $filePath);
                }
            }
        } catch (\Throwable $mailErr) {
            Log::warning("TenantBackupService: Could not dispatch backup email: " . $mailErr->getMessage());
        }

        return $backup;
    }

    /**
     * Prune old backups past retention threshold.
     */
    public function pruneOldBackups(Tenant $tenant, int $retentionDays = 30): int
    {
        if ($retentionDays <= 0) {
            return 0;
        }

        $cutoffDate = Carbon::now()->subDays($retentionDays);
        $expiredBackups = TenantBackup::where('tenant_id', $tenant->id)
            ->where('created_at', '<', $cutoffDate)
            ->get();

        $prunedCount = 0;
        foreach ($expiredBackups as $backup) {
            $fullPath = storage_path("app/{$backup->file_path}");
            if (File::exists($fullPath)) {
                File::delete($fullPath);
            }
            $backup->delete();
            $prunedCount++;
        }

        if ($prunedCount > 0) {
            Log::info("TenantBackupService: Pruned {$prunedCount} old backups older than {$retentionDays} days for Tenant #{$tenant->id}.");
        }

        return $prunedCount;
    }

    /**
     * Map tables for specific backup types
     */
    public function getTablesForType(string $type): array
    {
        return match ($type) {
            'subscribers_only' => [
                'tenant_customers',
                'tenant_coverage_zones',
            ],
            'mikrotik_rsc' => [
                'tenant_routers',
                'tenant_nas',
                'tenant_internet_packages',
                'tenant_ip_pools',
                'tenant_vlans',
                'tenant_routes',
                'tenant_olts',
                'tenant_onus',
            ],
            'billing_ledger' => [
                'tenant_customer_invoices',
                'tenant_customer_payments',
                'tenant_daily_cash_handovers',
                'tenant_expense_categories',
                'tenant_expense_transactions',
                'tenant_gateway_transactions',
                'tenant_reseller_invoices',
                'tenant_reseller_recharges',
                'tenant_wallets',
                'tenant_wallet_transactions',
            ],
            'system_config' => [
                'tenant_roles',
                'tenant_notification_templates',
                'tenant_automation_settings',
                'tenant_sms_gateways',
            ],
            default => [ // 'full_database'
                'tenant_customers',
                'tenant_coverage_zones',
                'tenant_routers',
                'tenant_nas',
                'tenant_internet_packages',
                'tenant_ip_pools',
                'tenant_vlans',
                'tenant_routes',
                'tenant_olts',
                'tenant_onus',
                'tenant_customer_invoices',
                'tenant_customer_payments',
                'tenant_daily_cash_handovers',
                'tenant_expense_categories',
                'tenant_expense_transactions',
                'tenant_gateway_transactions',
                'tenant_resellers',
                'tenant_reseller_bandwidth',
                'tenant_reseller_invoices',
                'tenant_reseller_recharges',
                'tenant_reseller_wallet_transactions',
                'tenant_reseller_escalations',
                'tenant_field_jobs',
                'tenant_installation_tasks',
                'tenant_roles',
                'tenant_staff_attendances',
                'tenant_notification_templates',
                'tenant_automation_settings',
                'tenant_sms_gateways',
                'tenant_activity_logs',
            ],
        };
    }
}
